name: flutter_ui_toolbox
description: "Flutter UI Toolbox is a lightweight, powerful, and easy-to-use package that provides essential extensions to simplify UI development in Flutter. From widget styling to context utilities, animations, device checks, and date formatting, this package offers dozens of time-saving utilities to boost productivity!"

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.5
repository: https://github.com/DevNimesh75/flutter_ui_toolbox
issue_tracker: https://github.com/DevNimesh75/flutter_ui_toolbox/issues

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #general packages
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  connectivity_plus: ^6.1.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - flutterutils